### ISSUE TITLE
Database destroy not clearing up correctly on Jest

### ISSUE THREAD

**Issue by klarkc** [pubkey/rxdb#2596]
## Case
Bug

## Issue
It's expected that jest exits after a database destroy, but it seems that something is being keep open:

```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

## Info
  - Environment: Node.js 14.11.0 (Jest 26.5.3)
  - Adapter: Tested with Memory and IndexedDB

## Code

```js
const pouchdbDebug = require('pouchdb-debug');
const { PouchDB, createRxDatabase, addRxPlugin } = require('rxdb');

// debug all
PouchDB.plugin(pouchdbDebug);
PouchDB.debug.enable('*');

const PouchDBAdapterMemory = require('pouchdb-adapter-memory');

addRxPlugin(PouchDBAdapterMemory);

it('creates and destroy database', () => createRxDatabase({
  name: 'foo',
  adapter: 'memory',
  eventReduce: true,
}).then((db) => db.destroy()));
```
## Reproduction

This repo has the reproduction code: https://github.com/klarkc/hang-test

```bash
yarn && yarn test
```

**Comment by klarkc** [comment]
I did run this helper with jest to give some clues:

```bash
yarn add --dev why-is-node-running
yarn why-is-node-running ./node_modules/.bin/jest test.spec.js --detectOpenHandles
```
output:
```
There are 7 handle(s) keeping the process running

# TTYWRAP
/home/klarkc/Sources/hang-test/node_modules/siginfo/index.js:3               - if (process.stderr.isTTY || force === true) {
/home/klarkc/Sources/hang-test/node_modules/why-is-node-running/include.js:3 - require('siginfo')(why, true)

# SIGNALWRAP
/home/klarkc/Sources/hang-test/node_modules/siginfo/index.js:3               - if (process.stderr.isTTY || force === true) {
/home/klarkc/Sources/hang-test/node_modules/why-is-node-running/include.js:3 - require('siginfo')(why, true)

# SIGNALWRAP
/home/klarkc/Sources/hang-test/node_modules/siginfo/index.js:6               - process.on('SIGUSR1', onsiginfo)
/home/klarkc/Sources/hang-test/node_modules/why-is-node-running/include.js:3 - require('siginfo')(why, true)

# TTYWRAP
/home/klarkc/Sources/hang-test/node_modules/jest-util/build/isInteractive.js:29 - !!process.stdout.isTTY && process.env.TERM !== 'dumb' && !_isCi().default;

# TTYWRAP
(unknown stack trace)

# PIPESERVERWRAP
/home/klarkc/Sources/hang-test/node_modules/broadcast-channel/src/methods/node.js:219 - server.listen(pathToSocket, async (err, res) => {
/home/klarkc/Sources/hang-test/node_modules/broadcast-channel/src/methods/node.js:213 - await new Promise((resolve, reject) => {
/home/klarkc/Sources/hang-test/node_modules/broadcast-channel/src/methods/node.js:397 - createSocketEventEmitter(channelName, uuid, paths),

# PIPEWRAP
/home/klarkc/Sources/hang-test/node_modules/broadcast-channel/src/methods/node.js:238 - client.connect(
/home/klarkc/Sources/hang-test/node_modules/broadcast-channel/src/methods/node.js:237 - return new Promise((res, rej) => {
/home/klarkc/Sources/hang-test/node_modules/broadcast-channel/src/methods/node.js:510 - const client = await openClientConnection(channelState.channelName, readerUuid);
/home/klarkc/Sources/hang-test/node_modules/broadcast-channel/src/methods/node.js:506 - .map(async (readerUuid) => {
```

**Comment by klarkc** [comment]
Might be related https://github.com/pubkey/broadcast-channel/issues/8

**Comment by klarkc** [comment]
I think I found the source: https://github.com/pubkey/broadcast-channel/blob/4d0fca350e26abceb692f43d8e64196431a17020/src/methods/node.js#L619

A workaround is to wait more then that timer, the destroy method of RxDatabase returns a promise, I think that this timer should be placed there: https://github.com/pubkey/rxdb/blob/a5311ee70947d2f976e8ed84b9c3817dc9a6a689/src/rx-database.ts#L378.

**Comment by pubkey** [comment]
I am not sure if I understood the root cause.
When RxDB destroys the database, and `setTimeout(() => channelState.socketEE.server.close(), 200);` is called. Should it then close the socket in all cases after 200ms and be able to exit the node process?

Do you think that is reproducible with plain broadcast-channel code?

**Comment by klarkc** [comment]
> When RxDB destroys the database, and setTimeout(() => channelState.socketEE.server.close(), 200); is called. Shouldn't it then close the socket in all cases after 200ms and be able to exit the node process?

The problem is broadcast-channel closes socket after the RxDB resolves (not before), and jest interprets it as "ok, I have to finish test, but we still have an open socket, so pause everything and warn user". I know this because when [we wait a bigger timeout (like 1500ms) it works](https://github.com/klarkc/hang-test/blob/resolve-timeout/test.spec.js#L19).

> Do you think that is reproducible with plain broadcast-channel code?

Certainly, I can open another issue there, but it will be the same issue, jest will hang because of broadcastChannel socket later close, and the code [comment says that there is not a solution yet](https://github.com/pubkey/broadcast-channel/blob/4d0fca350e26abceb692f43d8e64196431a17020/src/methods/node.js#L619).

**Comment by klarkc** [comment]
Another workaround (a lot better btw) is, in broadcast-channel side, callback or emit something to RxDB knows that the socket was closed, and then resolves its destroy call.

**Comment by pubkey** [comment]
Yes you are right.
The promise from `broadcastChannel.destroy()` should not resolve before all cleanup is done.

**Comment by pubkey** [comment]
Please check the latest release. This should be fixed now. Ping here if not.

**Comment by klarkc** [comment]
@pubkey still happening in 9.9.0, I've updated the reproduction repo with the latest release.

**Comment by stavalfi** [comment]
I have opened an issue with a minimal repo that reproduce this bug: https://github.com/pubkey/rxdb/issues/2938
