### ISSUE TITLE
ANNOUNCEMENT: The plans for the next major release

### ISSUE THREAD

**Issue by pubkey** [pubkey/rxdb#3168]
Hello everyone.
Atm I am planning the next major release where I want to change some breaking things.

The list of changes is maintained here:
https://github.com/pubkey/rxdb/blob/master/orga/before-next-major.md
Notice that not everything in this list will be in the next major release, it depends on how much time I have.

Please check the list and make pull requests with other changes you want to see.
Also I would be good to see some opinions here and I will answer open questions of course.

**Comment by bitlab-code** [comment]
- It would be useful to have composite primary keys, (defined in the json-schema through an array).

- Move pouchdb into a plugin, great! ...you can define a simple way to implement custom adapters.

**Comment by pubkey** [comment]
Composite primary keys is a good idea. Atm I often just concat a string but then have to parse it again which is error prone.

**Comment by kuka** [comment]
Top three: rxjs and pouchdb as plugins, and immutable rxdocs. Doesn’t seem like it’d be hard for people to update considering the possible breaking changes.

**Comment by phal0r** [comment]
From my experience, pouch and the revision logic does not bring much value, when not using couchdb. I use the graphql replication and pouch is only making things more complicated, i.e. no purge possible, soft delete needs to be implemented on application layer. The only thing, that is left, is the adapter system for all the environment and I think there are other lighter abstraction layers. So making it a plugin sounds very good.

Pouch as plugin and immutable docs sounds the most useful features to me.

Rxjs is really nice to work with, when it comes to coordinating async flows, which I guess all apps have. Currently we have 2 apps, where we use RxDB as state management tool and I really like the idea to have it persisted first and then queried when needed in contrast to redux and others. We use (or maybe abuse) redux-observables to connect our views to the observable layer without reducers. With the reactive queries this works like a charm and I have in mind to remove redux-observables for something more lightweight and better integrated to RxDB. 

Apart from that, we work on fuzzy search integration and evaluate fuse.js and lunr.js and how to integrate them into RxDB and the collections, but right now I would say, RxDB's plugin mechanism and hooks are flexible to enough to accomplish this.

This glued together with a faster persistence layer and immutable objects is really a nice and powerful stack to work with.

**Comment by Bessonov** [comment]
I'm pretty new to RxDB and I have following wishes:
- Joins. Currently I join multiple observables with `combineLatest`, group them with remeda's `groupBy` and `map` to a combined object. Somehow I had no success with `populate`. But even with it I would iterate over set of documents.
- RxDocument shouldn't mix RxDB methods/fields with user defined fields or methods. Currently, I use `.pipe(map(orgs => orgs.map(org => org.toJSON())))` or like.

But, well, maybe I use RxDB in a wrong way.

From high-level usage perspective, I use RxDB very similar to @phal0r : I don't use integrated sync option, because I have a use case that isn't easy to handle. Instead, I subscribe to change topic with GraphQL/WebSockets, fetch Data depending on incoming events and put it into RxDB. Components (react) observe data directly from RxDB.

**Comment by bitlab-code** [comment]
I understand that this adds complexity... 
but wanna suggest to consider to make the schema full compliance to json_schema (i.e. `anyOf`, ` allOf`, `oneOf`, default value for not root level fields, ...)

It's usual to use, and reuse, shared json_schema to handle other stuff like validations, etc...
in order to organize features in plugins, you can consider to delegate validation to a separate plugin that - for example - use third part library, like `Ajv`, for that

**Comment by pubkey** [comment]
@bitlab-code I tried to add this some time ago but it is very complex and painful. Also there are many cases where it is not clear how it can work properly with typescript or internal javascript properties. Please make a PR with a proposal but for me I think it is not worth the time.

**Comment by pubkey** [comment]
I released the beta of version `10.0.0`
Read about the changes [here](https://github.com/pubkey/rxdb/blob/release/10.0.0/orga/releases/10.0.0.md)

Please test it out, I rely on the community for testing.

**Comment by beruic** [comment]
@pubkey are composite primary keys ready in the beta?

At my work are transitioning a project from Dexie to RxDB, and I would like to jump onto 10 sooner rather than later, but we are currently adding relation collections for M2M relations, and they kinda need this feature.

**Comment by beruic** [comment]
Another few questions:

Our current stack consists of JavaScript + Dexie + CapacitorJS.
We are rewriting our current app towards TypeScript + Vue + RxDB + CapacitorJS.

Is there, or will there be a place we can find version 10 documentation?
(Like https://next.rxdb.info/ or something similar. I will also gladly contribute to documentation as soon as I start using it and gain understanding.)

When do you expect 10 to be production ready?
(I know this is probably not something you can answer, so I'm all happy if the answer is "when it's ready")

We are using IndexedDB as our backend, as our app is often offline.
Is there a better alternative to the current adapter, or will there be one in the near future?

**Comment by beruic** [comment]
Would be nice if it was possible to import without throwing events (to gain performance) when you need to import a large quantity of initial data.

**Comment by beruic** [comment]
Would be nice with a `.clear()` on both database and collections that will do a `.remove()` but also re-create using the same schema. This would especially be handy for unit test and scenarios when you need to clear, but don't want to run a lot of setup again.

**Comment by pubkey** [comment]
For the docs you have to clone the `release/10.0.0` branch and run `npm run docs:serve`. Or you can read the [readme files here](https://github.com/pubkey/rxdb/tree/release/10.0.0/docs-src)

@beruic composite primary keys are not implemented yet. They can be added later without breaking change.
I changed a lot on how event handling works, it is likely much faster now so you do not have to disable it.

My plan is to release `10.0.0` in about 2 weeks, depending if things have to be changed or not.

**Comment by phal0r** [comment]
@pubkey Congrats! Really amazing, that we already have a beta. A few questions regarding RxStorage:

I was digging a little bit in RxStorageInstance and you keep some assumptions, that pouch made, i.e. having a deleted flag to properly sync stuff. How would we deal with this interface with

a) undeletes: Deleting a record and it gets undeleted either on client or server side and should be used again. Can this be supported with other RxStorage implementations or would that break logic?

b) purging: Purging was requested but never implemented in pouch. What if we would implement such behavour in another RxStorage implementation?

Both of these features would make my life much easier and providing a faster and better to use storage abstraction would be something I could help with. Do you think this is possible with the current approach?

@beruic FYI: I am using RxDB with Capacitor in production aswell and we use cordova-sqlite plugin with a pouch adapter to store data in sqlite.

**Comment by pubkey** [comment]
@phal0r 

a) The deletion flag is send to the storage instance, exactly like currently in pouchdb. But the storage instance can internally handle the deletion process like it wants. It can store a deleted document like pouchdb does, or the storage instance could hard delete the document on the disc.
When a deleted document is inserted again (or gets somehow undeleted), the storageInstance has to handle it like a new insert and emit the correct insert events.

b) Purging can be internally implemented. I have thought about this a lot and I am pretty sure that can work with the current storage interface. Of course we only know for sure when someone has implemented a purging RxStorage.

RxDB does not rely on the internal revision handling of the storageInstance. Revisions could be kept there or not, this should not mather to RxDB.

**Comment by phal0r** [comment]
@pubkey Awesome. What do you currently recommend how to get started. I mean it's early stage and there is (understandably) not much documentation yet. Should I just take the RxStorage and RxStorageInstance interfaces and get started or are there interesting reads in the sourcecode, that could be helpful?

**Comment by pubkey** [comment]
@phal0r yes you can start with the [Interface](https://github.com/pubkey/rxdb/blob/release/10.0.0/src/types/rx-storage.interface.d.ts) I put every piece of documentation as code comments there. Also the [current tests](https://github.com/pubkey/rxdb/blob/release/10.0.0/test/unit/rx-storage-pouchdb.test.ts#L84) for the pouchdb RxStorage might be helpful as you can copy them and run them with your own implementation.

**Comment by pubkey** [comment]
Fixed some bugs in the beta. Released `10.0.0-beta.4`

**Comment by beruic** [comment]
@pubkey I still can't run v10. I run in a browser and the issue seems to be this line in `rxdb/dist/es/plugins/dev-mode/index.js`:
```
var deepFreeze = require('deep-freeze');
```

**Comment by beruic** [comment]
Changing the line to the below fixes it for me, although I'm not 100% sure of the implications.
```
import deepFreeze from "deep-freeze"
```

**Comment by pubkey** [comment]
@beruic  thanks for pointing that out. I released a new beta version with a fix.

**Comment by beruic** [comment]
@pubkey A few questions:

1. Are you deliberately developing without `package-lock.json`?

2. I'm trying to get a bit more into stuff so I may help fixing bugs and documentation, but everytime I run `npm run docs:install` I get:

```
> rxdb@10.0.0-beta.8 docs:install /home/jmk/git/rxdb
> gitbook install docs-src

Installing GitBook 3.2.3
/home/jmk/git/rxdb/node_modules/npm/node_modules/graceful-fs/polyfills.js:287
      if (cb) cb.apply(this, arguments)
                 ^

TypeError: cb.apply is not a function
    at /home/jmk/git/rxdb/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqCallback.oncomplete (fs.js:193:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rxdb@10.0.0-beta.8 docs:install: `gitbook install docs-src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rxdb@10.0.0-beta.8 docs:install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jmk/.npm/_logs/2021-06-29T07_42_49_302Z-debug.log
```

**Comment by pubkey** [comment]
@beruic 
1. Yes, I do not use a package-lock on purpose.
2. The install fails because of gitbooks install process. You have to downgrade nodejs like we do [in the CI](https://github.com/pubkey/rxdb/blob/master/.github/workflows/build.yml#L24)

**Comment by chrisdrackett** [comment]
I’m excited about the nee storages feature and I’m curious what the migration path might be. We have a react native app using react-native-sqlite pouch adaptor and I’m curious what it might look like if/when there is a SQLite storage option.

**Comment by beruic** [comment]
@pubkey regarding the Node version: Wouldn't it be sensible to base production to the current LTS (major version 14) instead of the previous unstable, short lived, already out of commision, version 13?

**Comment by beruic** [comment]
@pubkey It would be nice if you would use a `package-lock.json` or `yarn.lock` to get consistent installs across machines. This makes setup reproducible regardless of sub dependencies, and without, it is easy to get sub dependencies breaking stuff when setting up development on a new machine.

Also, re-installs tend to get faster when done often. For example in my daily work I often change branch and the versions change. To fix it I just run `npm ci` (we use `package-lock.json`) which deletes `[repository_root]/node_modules/` completely, and installs everything pretty fast, as it doesn't have to spend time resolving stuff, and even more so if you have a cache.

You can make the npm cache local to the repository by creating the file `.npmrc` with the following content:
```
cache=.npm
```
In our CI (on GitLab) we then cache the `[repository_root]/.npm/` directory based on the contents of `package.json` and `package-lock.json`, which saves a bunch of time in builds when dependencies does not change.
(Do not try to cache `[repository_root]/node_modules/`. That won't work for several reasons.)

I found a GitHub example for caching the npm cache [here](https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action). I would still move `.npm` to the repository directory, as I believe that has the benefit of being able to delete it for a single project at a time, and you can therefore screw around with it without breaking other projects.

You may also want to consider [`npm-shrinkwrap.json`](https://docs.npmjs.com/cli/v6/configuring-npm/shrinkwrap-json) instead of `package-lock.json`.

I would gladly make a PR, but that would require me being able to actually successfully setting up locally :wink:

**Comment by pubkey** [comment]
No I do not want a package-lock for libraries, they are made for apps.
When a user runs `npm install rxdb` it will not repsect the package-lock because the package-lock is not part of the npm module.
So when a subdependency changes in a breaking way, I want to have the CI failing because it would also fail to install rxdb on any new system. Having a package-lock would make things green in the CI but could fail when others install this library.

**Comment by pubkey** [comment]
@chrisdrackett I think the hardest part would be to transform the nosql-queries to sql queries. There are some libraries out there that already do that. Over all I think making a SQLite RxStorage would be relatively simple.
But notice that I myself will not implement any other RxStorage implementations. Mostly because I have enough to maintain already.

**Comment by chrisdrackett** [comment]
I'm more talking about if/when someone develops a RxStorage what the upgrade path would be for users that are currently running 9.x might be to an app built with 10.x and one of these new storages.

**Comment by pubkey** [comment]
@chrisdrackett I do not have a clear update path. On the client you might just delete the database and replicate from the server again.
On the server you could always use the json export and then import all again on the new version. This however might be too slow when much data needs to be migrated.

**Comment by pubkey** [comment]
Ongoing at https://github.com/pubkey/rxdb/issues/3279
