### ISSUE TITLE
database.remove() doesn't remove IndexedDB local documents

### ISSUE THREAD

**Issue by ofekd** [pubkey/rxdb#3319]
## Case
Bug

## Issue
GraphQL replication tried pulling new documents even after I ran `db.remove()`. Using the storage inspector in Firefox I could see the pull checkpoints were still there. I also suspect other local documents remain, but didn't have time to test.

In most browsers I can use `IndexedDB.databases()` to enumerate and delete them all manually. Does anyone know of a workaround for Firefox?

## Info
  - RxDB Version: 10.0.2
  - Environment: Browser
  - Adapter: IndexedDB
  - Stack: Typescript, Babel, Vue

**Comment by pubkey** [comment]
Thank you for reporting. Fixed in the attached commit.

**Comment by ofekd** [comment]
Thank you for fixing, much appreciated

**Comment by ofekd** [comment]
I have installed 10.0.3 and the pull checkpoint still persists after `remove()`.

Is there a way to get the list of the pouch IndexedDB databases? I would like to erase everything, regardless of `remove()`.

**Comment by pubkey** [comment]
I am not sure how to get all indexeddb databases.
Can you make a PR with a test to reproduce the problem?
In the new release we remove the whole local document store, so I do not see any way how the checkpoint can still persist.

**Comment by ofekd** [comment]
I see in the storage explorer that RxDB created IndexedDB databases for _both_ version 0 and version 1 of my schema (currently set to version 1 in the schema file). Is that intentional? I think it has something to do with it because the graphql pull checkpoint is set on the version 0 database. This was a fresh DB so it's not something that carried from old data.

**Comment by pubkey** [comment]
RxDB since version 10 creates a separate IndexedDB for local documents and 'normal' documents.
The local documents indexeddb always has version 0.

**Comment by ofekd** [comment]
I've added a failing test

![2021-08-10-124330](https://user-images.githubusercontent.com/6827960/128845484-ca0b3943-052b-4a8a-b252-21a4b6766d28.png)
