### ISSUE TITLE
Query optimizer doesn't finish (SQLite + React Native)

### ISSUE THREAD

**Issue by adam-lynch** [pubkey/rxdb#4804]
I set up a page in our web app which the query optimizer and it works. I set up the same thing in our expo / react native app and the promise `findBestIndex` returns never resolves. The parameters are identical except the storage used in the mobile app is SQLite + react-native-quick-sqlite.

I looked at the rxdb-premium source and found that `requestIdlePromise` never resolves. I replaced each `requestIdlePromise` call with a promisified timeout of 5ms and it works fine.

Versions:

- rxdb & rxdb-premium: 14.14.1
- expo: ^45.0.8
- react-native: 0.68.7
- react-native-quick-sqlite: ^7.0.0

**Comment by adam-lynch** [comment]
To be clear, I let it run for 20+ min. It never resolves.

**Comment by pubkey** [comment]
Hi @adam-lynch 

The code for `requestIdlePromise` is here https://github.com/pubkey/rxdb/blob/master/src/plugins/utils/utils-promise.ts#L37
Very likely it is throwing inside of the then-block and then the promise-queue is broken.

Can you check which error appears when you run the then-block directly in expo?

```
if (
                typeof window === 'object' &&
                (window as any)['requestIdleCallback']
            ) {
                (window as any)['requestIdleCallback'](res, {
                    timeout
                });
            } else {
                promiseWait(0).then(res);
            }

```

**Comment by adam-lynch** [comment]
Thanks, I can't easily test it so I'll test it when it's released. I didn't get around to reporting this but `wrappedValidateAjvStorage` also caused our mobile app to hang; maybe that was caused by the this `requestIdlePromise` bug too.

**Comment by pubkey** [comment]
I released a new version, please check.

**Comment by adam-lynch** [comment]
It's still hanging on those calls. I can't figure out why. `typeof requestIdleCallback === 'function'` is `true`.

I also saw that sometimes the `bulkWrite` call doesn't resolve, even though I see a "finishSqliteTransaction" log (from the `log` argument I pass to `getRxStorageSQLite`)... but I'm ignoring that for that now.

**Comment by pubkey** [comment]
React native also has a `requestIdleCallback` in the runtime. Therefore it should be true.
But still strange that it does not resolve, I will check.

**Comment by pubkey** [comment]
I checked on the RxDB react-native expo example and there the call to `requestIdlePromise` always resolves. Do you have something in your app that prevents the process from ever being idle?

```ts
console.log('requestIdlePromise START');
await requestIdlePromise();
console.log('requestIdlePromise END');
```

**Comment by adam-lynch** [comment]
I reduced my react-native app down to printing `Hello world` and that code above. The promise didn't resolve.

I found https://github.com/facebook/react-native/pull/29895, applied the change using patch-package, and now it resolves.

I don't know why it resolves for you and not for me. I would've guessed that our react-native versions are different but from that PR and associated issue, it seems like people are implying it's a bug in the latest version too. 

Even if it was the react-native version, I'd rather patch it than go through the hassle of updating the react-native version (and the other updates it would require).

Oh... I've only been testing this using iOS (simulator) and maybe you tested using Android, that could be it.

---

Since `findBestIndex` works now as expected (with that patch), so I'll close this issue.

---

A general point I'd like to make about `requestIdleCallback` (please correct me if I'm wrong). 

> This enables developers to perform background and _low priority_ work on the main event loop, without impacting latency-critical events such as animation and input response.

\- [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback).

I think it's reasonable that we should aim to have a little as possible running when calling `findBestIndex` or taking any performance measurements. Still, maybe `requestIdleCallback` isn't the best idea for `findBestIndex` based on that definition above, but really I just hope `requestIdleCallback` isn't used when we're using other rxdb functions (other than `findBestIndex`). I'd rather rxdb be prioritized.

**Comment by pubkey** [comment]
> Oh... I've only been testing this using iOS

That's it. I only tested it on android.
