### ISSUE TITLE
node:sqlite couldn't be found - react native, rxdb v15.29.0

### ISSUE THREAD

**Issue by meabed** [pubkey/rxdb#6291]
I recently upgraded to v15 from v14 and I got this error:

Issue with react-native:0.74 node:22 - everything working fine with v14 and early versions of v15

<img width="405" alt="image" src="https://github.com/user-attachments/assets/e8125867-3c59-46cf-bf28-85032bff7922">

**Comment by pubkey** [comment]
This is fixed in version `15.30.0`, please update to the latest one.

**Comment by meabed** [comment]
I did update but it's still happening, I will test again and update here

**Comment by pubkey** [comment]
@meabed I am so sorry, I did something wrong when merging. I will release 15.30.1 shortly with a fix.

**Comment by meabed** [comment]
Thank you so much, I saw the release I will test shortly and let you know.

**Comment by devtoil** [comment]
I am getting this error as well. Please let me know if I can provide any other details to help resolve the issue. Thanks!

**Comment by moritzlang** [comment]
Still getting this error on the latest release `15.30.1`

**Comment by moritzlang** [comment]
> Please check `15.30.2`

Issue is resolve with `15.30.2`, thank you 🙏
